//enum list
enum Category: String {

	//case
	case inc, ints, ints8, ints16, ints32, ints64, uints, uints8, uints16, uints32, uints64, floats32, floats64, bools, byte1, bytes, list_ints, list_string, list_float, map_string_string, map_string_bytes, map_string_bool, map_string_int, map_string_float64, map_string_any, map_int_string, map_int_int, map_int_bool, renameSQL, renameGO, renameJS_OK, mast_upper_go, intToSmallInt, sql_unique_u1_1, sql_unique_u1_2, sql_index1_1, sql_index1_2, sql_index1_3, sql_keys_1, sql_keys_2, sql_keys_3, sql_search, sql_get, sql_unique_x1, sql_unique_x2, sql_unique_x1_x2, sql_primary, sql_jsonb_index, time_duration, go_type_int_to_strings, public_field1, public_field2, public_field3, public_field_me1, public_field_me2, public_field_me3

	//name
	var string: String {
		get {
			switch self {
				case .inc:                     return "inc"
				case .ints:                    return "ints"
				case .ints8:                   return "ints8"
				case .ints16:                  return "ints16"
				case .ints32:                  return "ints32"
				case .ints64:                  return "ints64"
				case .uints:                   return "uints"
				case .uints8:                  return "uints8"
				case .uints16:                 return "uints16"
				case .uints32:                 return "uints32"
				case .uints64:                 return "uints64"
				case .floats32:                return "floats32"
				case .floats64:                return "floats64"
				case .bools:                   return "bools"
				case .byte1:                   return "byte1"
				case .bytes:                   return "bytes"
				case .list_ints:               return "list_ints"
				case .list_string:             return "list_string"
				case .list_float:              return "list_float"
				case .map_string_string:       return "map_string_string"
				case .map_string_bytes:        return "map_string_bytes"
				case .map_string_bool:         return "map_string_bool"
				case .map_string_int:          return "map_string_int"
				case .map_string_float64:      return "map_string_float64"
				case .map_string_any:          return "map_string_any"
				case .map_int_string:          return "map_int_string"
				case .map_int_int:             return "map_int_int"
				case .map_int_bool:            return "map_int_bool"
				case .renameSQL:               return "renameSQL"
				case .renameGO:                return "renameGO"
				case .renameJS_OK:             return "renameJS_OK"
				case .mast_upper_go:           return "mast_upper_go"
				case .intToSmallInt:           return "intToSmallInt"
				case .sql_unique_u1_1:         return "sql_unique_u1_1"
				case .sql_unique_u1_2:         return "sql_unique_u1_2"
				case .sql_index1_1:            return "sql_index1_1"
				case .sql_index1_2:            return "sql_index1_2"
				case .sql_index1_3:            return "sql_index1_3"
				case .sql_keys_1:              return "sql_keys_1"
				case .sql_keys_2:              return "sql_keys_2"
				case .sql_keys_3:              return "sql_keys_3"
				case .sql_search:              return "sql_search"
				case .sql_get:                 return "sql_get"
				case .sql_unique_x1:           return "sql_unique_x1"
				case .sql_unique_x2:           return "sql_unique_x2"
				case .sql_unique_x1_x2:        return "sql_unique_x1_x2"
				case .sql_primary:             return "sql_primary"
				case .sql_jsonb_index:         return "sql_jsonb_index"
				case .time_duration:           return "time_duration"
				case .go_type_int_to_strings:  return "go_type_int_to_strings"
				case .public_field1:           return "public_field1"
				case .public_field2:           return "public_field2"
				case .public_field3:           return "public_field3"
				case .public_field_me1:        return "public_field_me1"
				case .public_field_me2:        return "public_field_me2"
				case .public_field_me3:        return "public_field_me3"
			}
		}
	}
	
	//title
	var title: String {
		get {
			switch self {
				case .inc:                     return "Inc"
				case .ints:                    return "Ints"
				case .ints8:                   return "Ints8"
				case .ints16:                  return "Ints16"
				case .ints32:                  return "Ints32"
				case .ints64:                  return "Ints64"
				case .uints:                   return "Uints"
				case .uints8:                  return "Uints8"
				case .uints16:                 return "Uints16"
				case .uints32:                 return "Uints32"
				case .uints64:                 return "Uints64"
				case .floats32:                return "Floats32"
				case .floats64:                return "Floats64"
				case .bools:                   return "Bools"
				case .byte1:                   return "Byte1"
				case .bytes:                   return "Bytes"
				case .list_ints:               return "List_ints"
				case .list_string:             return "List_string"
				case .list_float:              return "List_float"
				case .map_string_string:       return "Map_string_string"
				case .map_string_bytes:        return "Map_string_bytes"
				case .map_string_bool:         return "Map_string_bool"
				case .map_string_int:          return "Map_string_int"
				case .map_string_float64:      return "Map_string_float64"
				case .map_string_any:          return "Map_string_any"
				case .map_int_string:          return "Map_int_string"
				case .map_int_int:             return "Map_int_int"
				case .map_int_bool:            return "Map_int_bool"
				case .renameSQL:               return "RenameSQL"
				case .renameGO:                return "RenameGO_OK"
				case .renameJS_OK:             return "RenameJS"
				case .mast_upper_go:           return "MAST_UPPER_GO"
				case .intToSmallInt:           return "IntToSmallInt"
				case .sql_unique_u1_1:         return "Sql_unique_u1_1"
				case .sql_unique_u1_2:         return "Sql_unique_u1_2"
				case .sql_index1_1:            return "Sql_index1_1"
				case .sql_index1_2:            return "Sql_index1_2"
				case .sql_index1_3:            return "Sql_index1_3"
				case .sql_keys_1:              return "Sql_keys_1"
				case .sql_keys_2:              return "Sql_keys_2"
				case .sql_keys_3:              return "Sql_keys_3"
				case .sql_search:              return "Sql_search"
				case .sql_get:                 return "Sql_get"
				case .sql_unique_x1:           return "Sql_unique_x1"
				case .sql_unique_x2:           return "Sql_unique_x2"
				case .sql_unique_x1_x2:        return "Sql_unique_x1_x2"
				case .sql_primary:             return "Sql_primary"
				case .sql_jsonb_index:         return "Sql_jsonb_index"
				case .time_duration:           return "Time_duration"
				case .go_type_int_to_strings:  return "Go_type_int_to_strings"
				case .public_field1:           return "Public_field1"
				case .public_field2:           return "Public_field2"
				case .public_field3:           return "Public_field3"
				case .public_field_me1:        return "Public_field_me1"
				case .public_field_me2:        return "Public_field_me2"
				case .public_field_me3:        return "Public_field_me3"
			}
		}
	}
	
}
